Repository CodelyTV/php-ddd-example, pull requests merged in 2020-06, with the labels that each got.

#161 Added make require compose interactive
  Makefile
Labels: Enhancement

#169 Use Behat directly
  composer.json
  composer.lock
Labels: size/xl

#172 Add minimum stability to composer
  composer.json
  composer.lock
Labels: size/m

#180 Add `ddd in php` course examples
  src/Mooc/Courses/Application/Create/CourseCreator.php
  src/Mooc/Courses/Application/Create/CreateCourseCommandHandler.php
  src/Mooc/Courses/Application/Find/CourseFinder.php
  src/Mooc/Courses/Application/Update/CourseRenamer.php
  src/Mooc/Courses/Domain/Course.php
  src/Mooc/Courses/Domain/CourseNotExist.php
  src/Mooc/Courses/Domain/CourseRepository.php
  src/Mooc/Courses/Infrastructure/Persistence/Doctrine/CourseIdType.php
  src/Mooc/Courses/Infrastructure/Persistence/DoctrineCourseRepository.php
  src/Mooc/Courses/Infrastructure/Persistence/FileCourseRepository.php
  src/Mooc/CoursesCounter/Application/Increment/CoursesCounterIncrementer.php
  src/Mooc/CoursesCounter/Application/Increment/IncrementCoursesCounterOnCourseCreated.php
  src/Mooc/CoursesCounter/Domain/CoursesCounter.php
  src/Mooc/CoursesCounter/Infrastructure/Persistence/Doctrine/CourseIdsType.php
  src/Mooc/Shared/Domain/Courses/CourseId.php
  src/Mooc/Shared/Domain/Videos/VideoUrl.php
  src/Mooc/Videos/Application/.gitkeep
  src/Mooc/Videos/Application/Create/CreateVideoCommand.php
  src/Mooc/Videos/Application/Create/CreateVideoCommandHandler.php
  src/Mooc/Videos/Application/Create/VideoCreator.php
  src/Mooc/Videos/Application/Find/FindVideoQuery.php
  src/Mooc/Videos/Application/Find/FindVideoQueryHandler.php
  src/Mooc/Videos/Application/Find/VideoFinder.php
  src/Mooc/Videos/Application/Find/VideoResponse.php
  src/Mooc/Videos/Application/Find/VideoResponseConverter.php
  src/Mooc/Videos/Application/Trim/TrimVideoCommand.php
  src/Mooc/Videos/Application/Trim/TrimVideoCommandHandler.php
  src/Mooc/Videos/Application/Trim/VideoTrimmer.php
  src/Mooc/Videos/Application/Update/VideoTitleUpdater.php
  src/Mooc/Videos/Domain/.gitkeep
  src/Mooc/Videos/Domain/Video.php
  src/Mooc/Videos/Domain/VideoCreatedDomainEvent.php
  src/Mooc/Videos/Domain/VideoFinder.php
  src/Mooc/Videos/Domain/VideoId.php
  src/Mooc/Videos/Domain/VideoNotFound.php
  src/Mooc/Videos/Domain/VideoRepository.php
  src/Mooc/Videos/Domain/VideoTitle.php
  src/Mooc/Videos/Domain/VideoType.php
  src/Mooc/Videos/Domain/Videos.php
  src/Mooc/Videos/Infrastructure/.gitkeep
  src/Mooc/Videos/Infrastructure/Persistence/Doctrine/Video.orm.yml
  src/Mooc/Videos/Infrastructure/Persistence/Doctrine/VideoIdType.php
  src/Mooc/Videos/Infrastructure/Persistence/Doctrine/VideoTitle.orm.yml
  src/Mooc/Videos/Infrastructure/Persistence/Doctrine/VideoType.orm.yml
  src/Mooc/Videos/Infrastructure/Persistence/VideoRepositoryMySql.php
  src/Shared/Domain/Second.php
  src/Shared/Domain/SecondsInterval.php
  src/Shared/Domain/ValueObject/IntValueObject.php
  tests/Mooc/Courses/Application/Create/CreateCourseCommandMother.php
  tests/Mooc/Courses/CoursesModuleUnitTestCase.php
  tests/Mooc/Courses/Domain/CourseCreatedDomainEventMother.php
  tests/Mooc/Courses/Domain/CourseIdMother.php
  tests/Mooc/Courses/Domain/CourseMother.php
  tests/Mooc/CoursesCounter/Domain/CoursesCounterMother.php
Labels: size/l
